INSERT INTO "Funder" VALUES
    ('dcenter6y','Arts'),
    ('mbartusek6z','Arts'),
    ('bmccumesky70','Food & Craft'),
    ('ccottel71','Arts'),
    ('ckeiling72','Games'),
    ('jhumber73','Film'),
    ('emacmearty74','Design & Tech'),
    ('bshone75','Film'),
    ('dagar76','Design & Tech'),
    ('reddolls77','Design & Tech'),
    ('bcashley78','Comics & Illustration'),
    ('bbutchart79','Comics & Illustration'),
    ('nfears7a','Games'),
    ('cmcillrick7b','Comics & Illustration'),
    ('kgamage7c','Arts'),
    ('hkitchen7d','Games'),
    ('ldelf7e','Comics & Illustration'),
    ('sconstanza7f','Music'),
    ('bgiffen7g','Design & Tech'),
    ('askea7h','Comics & Illustration'),
    ('koakshott7i','Games'),
    ('mfrantsev7j','Comics & Illustration'),
    ('smortlock7k',NULL),
    ('hcastellaccio7l','Comics & Illustration'),
    ('fphilimore7m','Design & Tech'),
    ('bcoppock7n','Food & Craft'),
    ('sberanek7o','Film'),
    ('sbythway7p','Food & Craft'),
    ('awoofendell7q','Food & Craft'),
    ('rdreinan7r','Food & Craft'),
    ('kweatherall7s','Arts'),
    ('lmechic7t','Games'),
    ('blemasney7u',NULL),
    ('cwildey7v','Games'),
    ('nwitcomb7w','Arts'),
    ('lspofforth7x','Arts'),
    ('sdrinkhall7y','Comics & Illustration'),
    ('penstone7z',NULL),
    ('bcampany80',NULL),
    ('dmanuello81','Design & Tech'),
    ('ecicci82','Food & Craft'),
    ('rmenere83','Music'),
    ('ctonge84','Film'),
    ('lreeds85','Food & Craft'),
    ('ahunnawill86','Arts'),
    ('achapelle87','Film'),
    ('cvella88','Music'),
    ('locodihie89','Food & Craft'),
    ('agirodier8a','Comics & Illustration'),
    ('jbuche8b','Games'),
    ('abarajaz8c','Arts'),
    ('rfishbourn8d','Games'),
    ('uheifer8e','Food & Craft'),
    ('dfuzzens8f','Food & Craft'),
    ('mgolds8g','Games'),
    ('ifones8h','Film'),
    ('cfishbie8i','Music'),
    ('tmatissoff8j','Comics & Illustration'),
    ('hmcgaraghan8k','Film'),
    ('kskipsey8l','Arts'),
    ('fdownes8m','Music'),
    ('oheineken8n','Food & Craft'),
    ('ljanssens8o',NULL),
    ('pbiggin8p','Games'),
    ('krubbert8q','Arts'),
    ('mnightingale8r','Games'),
    ('woleszczak8s',NULL),
    ('wstawell8t','Film'),
    ('jrickets8u','Arts'),
    ('jhekkert8v',NULL),
    ('cchastaing8w','Design & Tech'),
    ('dpope8x','Food & Craft'),
    ('jgoodlife8y','Food & Craft'),
    ('ggunthorp8z',NULL),
    ('rmeindl90','Design & Tech'),
    ('kkopta91','Games'),
    ('ccharlwood92',NULL),
    ('lmcgeouch93','Music'),
    ('mleask94',NULL),
    ('whance95',NULL),
    ('leisig96','Film'),
    ('scrysell97','Music'),
    ('lgait98','Arts'),
    ('jlardez99','Film'),
    ('hwardley9a','Games'),
    ('nhawton9b','Film'),
    ('tbrabon9c','Design & Tech'),
    ('lfarryan9d','Design & Tech'),
    ('csneaker9e','Music'),
    ('mberceros9f','Comics & Illustration'),
    ('sotteridge9g','Arts'),
    ('bdybald9h','Arts'),
    ('lkerfod9i',NULL),
    ('espeak9j','Comics & Illustration'),
    ('kpatrick9k','Comics & Illustration'),
    ('llumsdon9l','Games'),
    ('eswadlinge9m','Games'),
    ('eliptrod9n','Design & Tech'),
    ('amcphaden9o','Arts'),
    ('rlilloe9p','Games'),
    ('doakland9q','Arts'),
    ('croughley9r','Food & Craft'),
    ('afanton9s','Design & Tech'),
    ('tmaffione9t','Arts'),
    ('ccastellino9u','Comics & Illustration'),
    ('gde9v','Comics & Illustration'),
    ('lparnall9w','Music'),
    ('fnaisbet9x','Music'),
    ('mtregona9y','Music'),
    ('bcassella9z','Games'),
    ('bdoswella0','Arts'),
    ('pfeavioura1','Games'),
    ('rlovelocka2','Film'),
    ('wlindseya3','Games'),
    ('jatthowa4','Games'),
    ('cchitsona5','Comics & Illustration'),
    ('bedela6',NULL),
    ('eantonescua7','Arts'),
    ('ljansensa8','Food & Craft'),
    ('lgilchresta9',NULL),
    ('mshopcottaa','Food & Craft'),
    ('sgrzeskowskiab','Comics & Illustration'),
    ('cloosac','Design & Tech'),
    ('jsutorad',NULL),
    ('tsiebertae','Games'),
    ('dtimlinaf','Comics & Illustration'),
    ('lbewickeag','Film'),
    ('sbottrillah','Comics & Illustration'),
    ('ccolumai','Food & Craft'),
    ('ayurmanovevaj','Food & Craft'),
    ('kmcenteggartak',NULL),
    ('sholburyal','Games'),
    ('jsimounetam',NULL),
    ('btaxan','Music'),
    ('broderhamao','Games'),
    ('crexworthyap','Comics & Illustration'),
    ('dgaineaq','Film'),
    ('lcromiear',NULL),
    ('vhubandas','Food & Craft'),
    ('cramageat',NULL),
    ('eennorau','Film'),
    ('kmcphersonav',NULL),
    ('ehatcheraw','Music'),
    ('cfurnivalax','Games'),
    ('bambrogiottiay','Design & Tech'),
    ('jdollardaz','Games'),
    ('arangerb0',NULL),
    ('ahuegettb1','Games'),
    ('rloanb2',NULL),
    ('cfortinb3','Games'),
    ('fsnoddonb4','Games'),
    ('ejunesb5','Games'),
    ('stosneyb6','Film'),
    ('smccayb7','Food & Craft'),
    ('mhaskurb8','Food & Craft'),
    ('kduferieb9','Food & Craft'),
    ('klinnellba','Film'),
    ('mschulerbb','Games'),
    ('bborghesebc','Music'),
    ('ocawsybd',NULL),
    ('ciorizzibe','Games'),
    ('pdebf','Film'),
    ('maxelbg',NULL),
    ('abrieretonbh','Film'),
    ('akorneevbi','Comics & Illustration'),
    ('fwolledgebj','Arts'),
    ('lstonhousebk',NULL),
    ('cosmonbl',NULL),
    ('rdyshartbm','Music'),
    ('keyrebn','Arts'),
    ('ahayseldenbo','Games'),
    ('hhefnerbp','Comics & Illustration'),
    ('gyendlebq','Film'),
    ('nebbinbr','Comics & Illustration'),
    ('braynorbs','Arts'),
    ('gpetrollobt','Comics & Illustration'),
    ('mcornelissenbu','Food & Craft'),
    ('ghackingbv','Comics & Illustration'),
    ('tmccrannbw','Comics & Illustration'),
    ('bbraikenridgebx','Games'),
    ('slodekeby','Film'),
    ('lvernebz',NULL),
    ('hlaysonc0','Film'),
    ('rgierc1','Games'),
    ('rruttc2','Arts'),
    ('dmcmillianc3','Games'),
    ('sastlesc4','Comics & Illustration'),
    ('mmosedalec5','Music'),
    ('lcastlec6','Film'),
    ('eedyc7','Music'),
    ('btuveyc8','Film'),
    ('gbuffinc9','Music'),
    ('wrusteca','Food & Craft'),
    ('vbravingtoncb','Comics & Illustration'),
    ('aspunercc','Design & Tech'),
    ('cjosselcd',NULL),
    ('ecromiece','Games'),
    ('dstembridgecf','Food & Craft'),
    ('pstellinocg','Music'),
    ('kmccrumch','Film'),
    ('mrozenzweigci','Comics & Illustration'),
    ('llightbownecj','Food & Craft'),
    ('bnobleck','Games'),
    ('ecuttencl','Music'),
    ('mportiscm','Arts'),
    ('lveltmanncn','Comics & Illustration'),
    ('hcudbirdco','Film'),
    ('hdrysdallcp','Food & Craft'),
    ('vcarlesicq','Arts'),
    ('jgiovannazzicr','Design & Tech'),
    ('lfearneycs','Music'),
    ('gcarrivickct','Food & Craft'),
    ('mglowackicu','Food & Craft'),
    ('tholgancv','Games'),
    ('rawcockcw','Games'),
    ('cbuckstoncx',NULL),
    ('cgawkescy','Games'),
    ('ctroilletcz','Design & Tech'),
    ('lflaggd0','Arts'),
    ('dmurrelld1','Design & Tech'),
    ('cmcnaughtond2','Food & Craft'),
    ('sradloffd3','Design & Tech'),
    ('dmabed4','Design & Tech'),
    ('hnellerd5','Music'),
    ('ikiwitzd6','Games'),
    ('jhogbend7',NULL),
    ('gholylandd8','Games'),
    ('lalliboned9','Music'),
    ('scollefordda',NULL),
    ('ahaskerdb','Arts'),
    ('othodydc','Games'),
    ('ldickensdd','Games'),
    ('tollettde',NULL),
    ('rdaviouddf','Film'),
    ('jcuardalldg','Film'),
    ('ctenchdh','Music'),
    ('ishermandi','Arts'),
    ('cferrullidj','Games'),
    ('tjeskinsdk','Arts'),
    ('lgunnelldl',NULL),
    ('gleemingdm','Food & Craft'),
    ('jgrabbdn','Arts'),
    ('smcgettigando',NULL),
    ('gmaddamsdp','Food & Craft'),
    ('dsneppdq','Design & Tech'),
    ('lkeysalldr','Design & Tech'),
    ('dmarryattds','Food & Craft'),
    ('cmalloydt','Arts'),
    ('mlealedu','Arts'),
    ('zbartoszewiczdv',NULL);
INSERT INTO "Funder" VALUES
    ('jjanatadw','Music'),
    ('bmcgilvradx','Arts'),
    ('rwylddy','Arts'),
    ('josmonddz','Arts'),
    ('alassellse0','Arts'),
    ('jdodgshone1','Food & Craft'),
    ('rwoolwarde2','Food & Craft'),
    ('dpatronie3',NULL),
    ('couldcotte4','Games'),
    ('nwolfere5','Arts'),
    ('qhamelyne6','Arts'),
    ('pvampluse7','Comics & Illustration'),
    ('cbaillese8','Design & Tech'),
    ('wmagoverne9','Arts'),
    ('bsouthcombea','Design & Tech'),
    ('lcousineb','Design & Tech'),
    ('nwallingec','Games'),
    ('lkitteled','Film'),
    ('cbalharrieee',NULL),
    ('alandonef','Arts'),
    ('astickelseg','Comics & Illustration'),
    ('kjzakeh','Music'),
    ('mblagdenei','Food & Craft'),
    ('ikinnardej','Games'),
    ('bscottiniek','Games'),
    ('hmacgrathel','Film'),
    ('sbelliardem','Food & Craft'),
    ('abrickstocken','Film'),
    ('atregidoeo',NULL),
    ('rkenelinep','Food & Craft'),
    ('aoehmeeq','Food & Craft'),
    ('dpeatheyjohnser','Comics & Illustration'),
    ('atoynbeees','Comics & Illustration'),
    ('lantoniatet','Music'),
    ('dgallihaulkeu','Food & Craft'),
    ('wwakeleyev','Film'),
    ('chartfleetew','Film'),
    ('dsnalhamex','Comics & Illustration'),
    ('jmockfordey','Film'),
    ('jweekesez','Food & Craft'),
    ('lfreckinghamf0','Design & Tech'),
    ('tmozzinif1','Games'),
    ('cbootmanf2','Music'),
    ('lbaudinellif3',NULL),
    ('ecleverleyf4','Design & Tech'),
    ('rtorrif5','Comics & Illustration'),
    ('dpetticrowf6','Games'),
    ('cdigglesf7','Comics & Illustration'),
    ('tmcgaughief8','Arts'),
    ('gtomasuttif9','Food & Craft'),
    ('acherrymanfa','Design & Tech'),
    ('sanderssonfb',NULL),
    ('mdanickfc','Design & Tech'),
    ('ebifieldfd','Design & Tech'),
    ('kyashinfe','Design & Tech'),
    ('ldeff','Food & Craft'),
    ('ehiddsleyfg','Arts'),
    ('amorriesonfh','Comics & Illustration'),
    ('kcurtisfi','Games'),
    ('hcrinkleyfj','Music'),
    ('tloddonfk','Food & Craft'),
    ('dmcdonaghfl','Film'),
    ('dfoordfm','Film'),
    ('abrandrethfn',NULL),
    ('mdeningtonfo','Music'),
    ('lpeddiefp',NULL),
    ('ltaffiefq','Design & Tech'),
    ('rogianyfr','Music'),
    ('mdreifs','Film'),
    ('drozenbaumft','Comics & Illustration'),
    ('wvennersfu','Arts'),
    ('smactrustramfv','Comics & Illustration'),
    ('emaiseyfw','Design & Tech'),
    ('tmclemanfx','Music'),
    ('irowettfy','Games'),
    ('gwelfarefz','Comics & Illustration'),
    ('dpollardg0','Music'),
    ('tbartoccig1','Games'),
    ('cfabbg2',NULL),
    ('mbevilleg3','Food & Craft'),
    ('smattamg4','Food & Craft'),
    ('hquadrig5',NULL),
    ('kmorang6',NULL),
    ('jmcmeylerg7','Design & Tech'),
    ('ehardisong8','Games'),
    ('mhedinghamg9','Comics & Illustration'),
    ('mmicheliga','Games'),
    ('fbeamsgb','Music'),
    ('lcalladinegc','Arts'),
    ('alaidlowgd','Music'),
    ('hgabrielyge',NULL),
    ('sroizngf','Film'),
    ('fdufourgg','Food & Craft'),
    ('nwillmotgh','Film'),
    ('cmanisgi',NULL),
    ('mmcettrickgj',NULL),
    ('kmedlinggk',NULL),
    ('fogl','Comics & Illustration'),
    ('baikettgm',NULL),
    ('tradbornegn','Design & Tech'),
    ('ctamblingsongo','Food & Craft'),
    ('hmaudlengp','Comics & Illustration'),
    ('fgrimmolbygq','Games'),
    ('rscotchergr','Comics & Illustration'),
    ('niiannonegs','Games'),
    ('gstanfieldgt','Food & Craft'),
    ('hcasollagu','Food & Craft'),
    ('mdoickgv','Food & Craft'),
    ('jhillamgw','Film'),
    ('kskipseagx','Games'),
    ('asutehallgy','Design & Tech'),
    ('otinsongz','Food & Craft'),
    ('dindeh0','Food & Craft'),
    ('fhaironh1','Food & Craft'),
    ('bdorwoodh2',NULL),
    ('tnelmh3','Comics & Illustration'),
    ('cgisburnh4','Food & Craft'),
    ('nduryh5','Design & Tech'),
    ('ssmowtonh6','Arts'),
    ('mrabath7','Design & Tech'),
    ('tdoerrlingh8','Design & Tech'),
    ('adangerfieldh9','Design & Tech'),
    ('lrotherforthha','Arts'),
    ('lnovellihb','Arts'),
    ('ccomussohc','Games'),
    ('jgotfreyhd','Music'),
    ('browcastlehe','Film'),
    ('awhoppleshf','Music'),
    ('skernellhg',NULL),
    ('jmadgwichhh','Comics & Illustration'),
    ('tblundonhi','Food & Craft'),
    ('twatkisshj','Film'),
    ('smegaheyhk','Music'),
    ('bmeaneyhl','Arts'),
    ('lcahnhm','Games'),
    ('menstenhn','Music'),
    ('abenneho',NULL),
    ('respinoshp','Food & Craft'),
    ('afellonhq','Comics & Illustration'),
    ('oodunniomhr','Music'),
    ('cpaprotnyhs','Comics & Illustration'),
    ('cingmanht','Food & Craft'),
    ('dmottehu','Film'),
    ('tleggatthv','Design & Tech'),
    ('eheavyhw','Design & Tech'),
    ('mdehx','Games'),
    ('hprittyhy','Design & Tech'),
    ('lashcrofthz','Arts'),
    ('alogesi0','Music'),
    ('hkingstnei1','Games'),
    ('frheadi2','Food & Craft'),
    ('mandriulisi3','Comics & Illustration'),
    ('fgarfiti4','Music'),
    ('kwestbyi5','Music'),
    ('kmarjorami6','Games'),
    ('smussillii7',NULL),
    ('sarguilei8',NULL),
    ('rbosencei9',NULL),
    ('eweylandia','Food & Craft'),
    ('bgladebeckib','Comics & Illustration'),
    ('acounihanic','Games'),
    ('dbothenid','Film'),
    ('vmartiniie','Arts'),
    ('pfordif','Design & Tech'),
    ('woharneyig','Food & Craft'),
    ('bfilyakovih','Games'),
    ('lhorleyii',NULL),
    ('ssarverij','Arts'),
    ('slordingik','Comics & Illustration'),
    ('gwillsheeil','Film'),
    ('fveaseyim','Design & Tech'),
    ('jchadwinin','Games'),
    ('mhumberstonio','Comics & Illustration'),
    ('cmellmothip','Music'),
    ('gtotaroiq','Arts'),
    ('jfarishir','Design & Tech'),
    ('mgatheralis','Food & Craft'),
    ('jsalamanit',NULL),
    ('bfoleyiu','Film'),
    ('tnevinsiv','Design & Tech'),
    ('ahertwelliw','Arts'),
    ('jknellerix','Music'),
    ('jyakunkiniy','Music'),
    ('tinnettiz','Food & Craft'),
    ('jpedlowj0','Music'),
    ('jbissillj1','Music'),
    ('mjustej2','Arts'),
    ('csandarsj3','Music'),
    ('jlowrej4','Music'),
    ('tgrishmanovj5','Games'),
    ('hlangstaffj6','Arts'),
    ('nmcgerrj7',NULL),
    ('rjakoviljevicj8',NULL),
    ('bpothecaryj9','Food & Craft'),
    ('cmacsweeneyja','Music'),
    ('tbinehamjb','Games'),
    ('lriddalljc','Games'),
    ('vdejd','Food & Craft'),
    ('cmatveikoje',NULL),
    ('bwannelljf','Games'),
    ('cmaddamsjg','Music'),
    ('rwerendelljh','Arts'),
    ('gpembleji','Games'),
    ('bbrodwayjj','Design & Tech'),
    ('sdunphyjk','Comics & Illustration'),
    ('cfisherjl','Games'),
    ('ngentiryjm',NULL),
    ('mdrinkeljn','Film'),
    ('pkiddejo','Arts'),
    ('wbritlandjp','Arts'),
    ('dhooksjq',NULL),
    ('ccalbertjr','Arts'),
    ('pdejs','Arts'),
    ('jgoodrickejt','Music'),
    ('fkirsopju','Arts'),
    ('oyankinjv','Music'),
    ('josbournejw','Film'),
    ('psyrettjx','Film'),
    ('peasthamjy','Film'),
    ('dlawlorjz','Comics & Illustration'),
    ('sgyenesk0','Arts'),
    ('epeckittk1','Games'),
    ('garnettk2','Food & Craft'),
    ('fduchartk3',NULL),
    ('dspickettk4','Games'),
    ('cgrattonk5','Comics & Illustration'),
    ('dshimmingsk6','Music'),
    ('nferrinik7','Games'),
    ('ghawsonk8','Music'),
    ('rpeppink9','Food & Craft'),
    ('ktrendleka','Food & Craft'),
    ('mansillkb','Food & Craft'),
    ('mkobpakc',NULL),
    ('alodekekd','Film'),
    ('rmardenke','Film'),
    ('kstrappkf','Comics & Illustration'),
    ('afurberkg','Games'),
    ('igavriellikh','Design & Tech'),
    ('kcamerelloki','Comics & Illustration'),
    ('vtointonkj','Games'),
    ('trylattkk','Games'),
    ('mvitlerkl','Design & Tech'),
    ('fsivewrightkm','Food & Craft'),
    ('sinnocentkn','Food & Craft'),
    ('selcomeko','Comics & Illustration'),
    ('hcrabbekp','Games'),
    ('pwhyekq','Comics & Illustration'),
    ('ktadmankr','Comics & Illustration'),
    ('dnugentks','Food & Craft'),
    ('rdurrellkt','Games');
INSERT INTO "Funder" VALUES
    ('ethorsenku','Games'),
    ('pmedlingkv','Arts'),
    ('kjanosevickw','Food & Craft'),
    ('lchaveskx',NULL),
    ('jgoslandky','Film'),
    ('cpopworthkz','Games'),
    ('finklesl0',NULL),
    ('facuttl1','Comics & Illustration'),
    ('mparnalll2',NULL),
    ('dheliotl3','Games'),
    ('rkamenal4','Comics & Illustration'),
    ('tbuchaml5','Arts'),
    ('bvaggersl6','Design & Tech'),
    ('svanl7','Arts'),
    ('ateliginl8','Games'),
    ('lpegraml9','Design & Tech'),
    ('bgendrickela','Games'),
    ('tashbridgelb','Arts'),
    ('lcuncarrlc','Film'),
    ('wfowleld','Arts'),
    ('gthreshle','Music'),
    ('sklamptlf','Design & Tech'),
    ('rbinnalllg','Design & Tech'),
    ('smortonlh','Food & Craft'),
    ('ncracoeli','Music'),
    ('bpueslj','Games'),
    ('mguilloudlk','Comics & Illustration'),
    ('mlarcierell','Design & Tech'),
    ('smcareaveylm','Music'),
    ('mponterln','Games'),
    ('krowetlo','Games'),
    ('focrowleylp','Comics & Illustration'),
    ('vheadinglq','Design & Tech'),
    ('aellicklr','Music'),
    ('jsoreyls','Games'),
    ('ututherlt','Film'),
    ('mmulranlu','Film'),
    ('hwillgrasslv','Music'),
    ('lsprowlelw','Comics & Illustration'),
    ('mdoxseylx','Games'),
    ('atatnellly','Arts'),
    ('rgoinglz','Design & Tech'),
    ('ajecksm0','Food & Craft'),
    ('bcourtonnem1','Music'),
    ('fvanm2','Design & Tech'),
    ('ybrazelm3','Food & Craft'),
    ('rodugganm4','Comics & Illustration'),
    ('ahempshallm5',NULL),
    ('akocherm6','Food & Craft'),
    ('akorpolakm7',NULL),
    ('mcolquytem8',NULL),
    ('cshuardm9','Arts'),
    ('aassardma','Film'),
    ('gwebbermb','Games'),
    ('wricharzmc','Design & Tech'),
    ('mecclesmd','Food & Craft'),
    ('ccordeletteme','Arts'),
    ('gpesicmf','Design & Tech'),
    ('ebarzmg','Arts'),
    ('rdionisiimh','Games'),
    ('bwanklynmi','Comics & Illustration'),
    ('mcicettimj','Arts'),
    ('ftredgetmk','Food & Craft'),
    ('zslineyml','Arts'),
    ('nridolfomm','Comics & Illustration'),
    ('calevequemn','Games'),
    ('wmacfaddenmo','Music'),
    ('ksaynormp','Arts'),
    ('amargiottamq','Design & Tech'),
    ('cmaseykmr','Food & Craft'),
    ('tminchellams','Music'),
    ('ndinkinmt',NULL),
    ('mpashlermu','Comics & Illustration'),
    ('pyomv','Comics & Illustration'),
    ('dsheklemw','Film'),
    ('cavesmx','Food & Craft'),
    ('crathemy','Food & Craft'),
    ('koflahertymz',NULL),
    ('jconerdingn0','Design & Tech'),
    ('rkervinn1','Arts'),
    ('cwhippn2',NULL),
    ('gdin3','Music'),
    ('rvermann4','Music'),
    ('gwibrewn5','Games'),
    ('vpercifulln6','Music'),
    ('hskahilln7','Music'),
    ('kdooreyn8','Arts'),
    ('ofoloninn9','Comics & Illustration'),
    ('mminellina','Arts'),
    ('qbeangenb','Games'),
    ('soakebync','Design & Tech'),
    ('stomkiesnd','Food & Craft'),
    ('ldalgarnochtne','Food & Craft'),
    ('kbolandnf','Games'),
    ('mtrevenng','Games'),
    ('kpierronh','Film'),
    ('lsannesni','Comics & Illustration'),
    ('vlammasnj',NULL),
    ('ecalvienk','Food & Craft'),
    ('rbirdseyenl','Design & Tech'),
    ('nmulhollandnm','Music'),
    ('lchellamnn','Film'),
    ('jlaurantno','Arts'),
    ('fleachmannp',NULL),
    ('dmonteauxnq','Arts'),
    ('habsolomnr','Design & Tech'),
    ('wgreberns','Arts'),
    ('jstnt','Food & Craft'),
    ('bkinvernu','Arts'),
    ('abruneaunv','Design & Tech'),
    ('jkyntonnw','Film'),
    ('pmcturleynx',NULL),
    ('lsweedyny','Film'),
    ('kdungaynz','Film'),
    ('alavalo0','Comics & Illustration'),
    ('dharrello1','Design & Tech'),
    ('tneateo2','Film'),
    ('ldrysdaleo3','Arts'),
    ('pruzico4','Comics & Illustration'),
    ('rdudeneyo5','Games'),
    ('iwoolveridgeo6','Design & Tech'),
    ('fwainwrighto7',NULL),
    ('ghabbleo8','Comics & Illustration'),
    ('mthirlawayo9','Design & Tech'),
    ('gmorsonoa','Games'),
    ('ljoblinob','Games'),
    ('ljaquemaroc','Design & Tech'),
    ('lpietsmaod','Arts'),
    ('iboardoe','Comics & Illustration'),
    ('rbrownbridgeof','Design & Tech'),
    ('jraatzog','Music'),
    ('sdummiganoh','Arts'),
    ('ctweddleoi','Games'),
    ('cpatchingoj',NULL),
    ('lcoopeok','Food & Craft'),
    ('boheneghanol','Comics & Illustration'),
    ('gwindrumom','Games'),
    ('drabbeton',NULL),
    ('bkisbeyoo','Film'),
    ('vpepperellop','Music'),
    ('ccornbilloq','Comics & Illustration'),
    ('pridgesor','Comics & Illustration'),
    ('rglynnos','Food & Craft'),
    ('jfirthot','Food & Craft'),
    ('slangforthou','Food & Craft'),
    ('aolearyov','Comics & Illustration'),
    ('ccroomeow','Games'),
    ('smilburneox','Music'),
    ('hmilchoy','Design & Tech'),
    ('vinfantinooz','Comics & Illustration'),
    ('okerstingp0',NULL),
    ('dhadwenp1','Film'),
    ('bwoodruffep2','Design & Tech'),
    ('rhowbrookp3',NULL),
    ('bgiovannaccip4','Film'),
    ('thoulisonp5','Comics & Illustration'),
    ('owinsletp6','Food & Craft'),
    ('dyurygynp7',NULL),
    ('dvitetp8','Music'),
    ('hbrimilcombep9','Music'),
    ('againsfordpa','Food & Craft'),
    ('igirlingpb','Music'),
    ('clintheadpc',NULL),
    ('minchleypd','Design & Tech'),
    ('mhullandpe','Film'),
    ('mcavenpf','Games'),
    ('eshurrockpg','Film'),
    ('tdurranceph','Games'),
    ('asleggpi','Music'),
    ('zbrislawnpj','Food & Craft'),
    ('cstakerpk','Design & Tech'),
    ('srathbornepl','Food & Craft'),
    ('fscoffinspm',NULL),
    ('abemandpn','Comics & Illustration'),
    ('cdurrampo','Comics & Illustration'),
    ('ekenefordepp','Film'),
    ('pninnottipq','Film'),
    ('coharneypr','Food & Craft'),
    ('seilerps','Food & Craft'),
    ('egypsonpt','Design & Tech'),
    ('rtoffelpu','Design & Tech'),
    ('kkimmittpv','Design & Tech'),
    ('ajacksonpw',NULL),
    ('sgaymerpx',NULL),
    ('amauspy','Comics & Illustration'),
    ('bmarquisspz','Design & Tech'),
    ('mmccoughanq0','Food & Craft'),
    ('asurgenerq1','Music'),
    ('ygozzettq2','Music'),
    ('boxladeq3',NULL),
    ('gorgeeq4',NULL),
    ('estangroomq5','Design & Tech'),
    ('aquinbyq6','Design & Tech'),
    ('tcawthryq7','Arts'),
    ('mkauscheq8','Music'),
    ('ltabramq9','Film'),
    ('dgoodrightqa','Food & Craft'),
    ('ewoolnoughqb','Food & Craft'),
    ('kkleinmintzqc',NULL),
    ('wkemmqd','Games'),
    ('tmoulsdale0','Arts'),
    ('rsawbridge1','Games'),
    ('mwalshaw2',NULL),
    ('koxbury3','Arts'),
    ('ppickring4',NULL),
    ('kclynter5','Design & Tech'),
    ('cbrowning6','Music'),
    ('cyeowell7','Food & Craft'),
    ('fyashin8','Comics & Illustration'),
    ('ymatzel9','Comics & Illustration'),
    ('vblythina','Film'),
    ('ctyrieb','Games'),
    ('alivettc','Arts'),
    ('efullagerd','Games'),
    ('evittete','Music'),
    ('gdionisf','Food & Craft'),
    ('ebraybrookg','Film'),
    ('ntwinborneh','Design & Tech'),
    ('lbohlingi','Music'),
    ('alyvonj','Design & Tech'),
    ('ahaslockk','Arts'),
    ('bjakubowskyl','Design & Tech'),
    ('ssandbachm','Food & Craft'),
    ('wstoilen','Arts'),
    ('tthebeo',NULL),
    ('bquarlessp','Arts'),
    ('eshippeyq','Comics & Illustration'),
    ('hmcnabbr','Film'),
    ('dloudons','Comics & Illustration'),
    ('acameranat','Comics & Illustration'),
    ('mhugou','Food & Craft'),
    ('agallamorev','Food & Craft'),
    ('escotneyw','Film'),
    ('amatex','Design & Tech'),
    ('kiannelliy','Music'),
    ('acholtonz','Comics & Illustration'),
    ('cguthrie10','Design & Tech'),
    ('dleyman11',NULL),
    ('rrodden12','Design & Tech'),
    ('asrawley13','Comics & Illustration'),
    ('ceates14',NULL),
    ('arivard15','Comics & Illustration'),
    ('awasselin16','Design & Tech'),
    ('lmcveighty17','Games'),
    ('cjoisce18','Food & Craft'),
    ('dwheeler19','Games'),
    ('wragborne1a','Film'),
    ('rvibert1b','Design & Tech'),
    ('ltrenholme1c','Design & Tech'),
    ('lbunting1d','Food & Craft');
INSERT INTO "Funder" VALUES
    ('gjurisch1e','Food & Craft'),
    ('bfrankis1f','Games'),
    ('kcasbon1g','Film'),
    ('gharrower1h','Design & Tech'),
    ('shellen1i','Arts'),
    ('lpaggitt1j','Comics & Illustration'),
    ('ijakubovicz1k','Games'),
    ('hboyall1l',NULL),
    ('charbert1m','Music'),
    ('dgrishakov1n','Comics & Illustration'),
    ('fpeschet1o','Comics & Illustration'),
    ('vthirlaway1p','Film'),
    ('lhairyes1q',NULL),
    ('tyesenin1r','Music'),
    ('bwaldren1s','Games'),
    ('mvirgin1t','Music'),
    ('mfumagalli1u','Film'),
    ('cdi1v','Games'),
    ('mbarrowcliff1w','Arts'),
    ('wegiloff1x','Comics & Illustration'),
    ('dnewis1y','Film'),
    ('tcaldecourt1z','Games'),
    ('afeldhorn20','Games'),
    ('bherche21','Food & Craft'),
    ('bmandell22','Arts'),
    ('sluckes23','Comics & Illustration'),
    ('sforsard24','Comics & Illustration'),
    ('ebatcock25',NULL),
    ('dbudgen26','Food & Craft'),
    ('mpannaman27','Design & Tech'),
    ('rshrubb28','Games'),
    ('esummerscales29',NULL),
    ('wmcorkill2a',NULL),
    ('bdybell2b','Music'),
    ('dfilipov2c','Music'),
    ('aiannuzzi2d','Games'),
    ('asworn2e',NULL),
    ('jtournay2f','Food & Craft'),
    ('fhawking2g','Arts'),
    ('mslimme2h','Design & Tech'),
    ('gpatzelt2i','Food & Craft'),
    ('dtheaker2j','Arts'),
    ('csone2k','Film'),
    ('akerrod2l','Food & Craft'),
    ('dsweatman2m','Comics & Illustration'),
    ('piskowicz2n','Design & Tech'),
    ('fprator2o','Film'),
    ('gsennett2p','Film'),
    ('ndurham2q','Design & Tech'),
    ('gdoucette2r','Design & Tech'),
    ('hsmelley2s',NULL),
    ('gromand2t','Music'),
    ('ffazackerley2u','Comics & Illustration'),
    ('gkingstne2v','Games'),
    ('cdollen2w','Arts'),
    ('ebleacher2x','Film'),
    ('gkinkead2y','Comics & Illustration'),
    ('rposten2z','Design & Tech'),
    ('nhymer30','Film'),
    ('cgofforth31','Games'),
    ('oswainger32',NULL),
    ('dalred33','Film'),
    ('kspeke34','Music'),
    ('aminshull35','Film'),
    ('aeccleshall36','Design & Tech'),
    ('clongstreeth37','Design & Tech'),
    ('amallinson38',NULL),
    ('ghallad39','Food & Craft'),
    ('gcassimer3a','Arts'),
    ('rwilloughey3b','Music'),
    ('fjanicek3c','Music'),
    ('kbaybutt3d','Comics & Illustration'),
    ('sditer3e','Food & Craft'),
    ('ddenisot3f','Food & Craft'),
    ('fmattedi3g','Comics & Illustration'),
    ('vgeraudy3h','Games'),
    ('kesposita3i','Arts'),
    ('jsouthan3j','Food & Craft'),
    ('mellery3k','Games'),
    ('edudson3l','Food & Craft'),
    ('cbenedicte3m','Film'),
    ('mprevett3n',NULL),
    ('rholt3o','Food & Craft'),
    ('fmclaren3p','Film'),
    ('graven3q','Arts'),
    ('bjeanes3r','Arts'),
    ('calabastar3s','Comics & Illustration'),
    ('jranyelld3t','Design & Tech'),
    ('astowgill3u','Games'),
    ('kduferie3v','Music'),
    ('csatterley3w','Food & Craft'),
    ('gguswell3x','Comics & Illustration'),
    ('jsteart3y','Games'),
    ('stottman3z','Arts'),
    ('csouttar40','Arts'),
    ('bfomichkin41','Arts'),
    ('tmunnings42',NULL),
    ('alogan43','Comics & Illustration'),
    ('mmotten44','Design & Tech'),
    ('jlesurf45','Arts'),
    ('cspatoni46',NULL),
    ('opringer47','Film'),
    ('bscranedge48','Comics & Illustration'),
    ('nmayberry49','Comics & Illustration'),
    ('plucus4a','Food & Craft'),
    ('jtatteshall4b','Film'),
    ('cdrewes4c','Design & Tech'),
    ('rdomonkos4d','Design & Tech'),
    ('ccoll4e','Film'),
    ('sspancock4f','Music'),
    ('normes4g','Comics & Illustration'),
    ('dlambal4h','Design & Tech'),
    ('ade4i','Food & Craft'),
    ('fgallahar4j','Design & Tech'),
    ('schadbourne4k',NULL),
    ('tkilliam4l',NULL),
    ('ckrabbe4m','Music'),
    ('pseeborne4n','Music'),
    ('bbeek4o','Comics & Illustration'),
    ('mvallerine4p','Comics & Illustration'),
    ('bdimelow4q','Film'),
    ('kmaundrell4r','Games'),
    ('ealeksic4s','Food & Craft'),
    ('vkurt4t',NULL),
    ('bpottell4u',NULL),
    ('lfathers4v',NULL),
    ('sdallison4w','Music'),
    ('akynnd4x','Film'),
    ('kvelareal4y','Arts'),
    ('ttorresi4z','Food & Craft'),
    ('atitchard50','Food & Craft'),
    ('awyley51','Comics & Illustration'),
    ('jroutley52','Games'),
    ('cfergyson53','Comics & Illustration'),
    ('mpikett54','Film'),
    ('fconklin55','Design & Tech'),
    ('rgiorgielli56','Arts'),
    ('rgabbatiss57','Film'),
    ('ppostan58','Food & Craft'),
    ('ccavie59','Comics & Illustration'),
    ('clafflina5a',NULL),
    ('kphetteplace5b','Music'),
    ('shuddlestone5c','Music'),
    ('mkilfedder5d','Music'),
    ('jagneau5e','Film'),
    ('blassetter5f','Comics & Illustration'),
    ('gbreissan5g','Music'),
    ('ssyres5h','Food & Craft'),
    ('gandersson5i','Music'),
    ('lpresland5j','Design & Tech'),
    ('bgeffe5k',NULL),
    ('atolossi5l','Arts'),
    ('melderbrant5m','Games'),
    ('gstockport5n','Design & Tech'),
    ('ahandman5o','Food & Craft'),
    ('cholley5p','Design & Tech'),
    ('adoghartie5q','Arts'),
    ('dlofthouse5r','Food & Craft'),
    ('gpyper5s','Music'),
    ('mshervil5t','Design & Tech'),
    ('jkidney5u','Film'),
    ('rmolines5v',NULL),
    ('jfritz5w','Music'),
    ('rdangerfield5x','Film'),
    ('nflawith5y','Film'),
    ('ncookson5z','Comics & Illustration'),
    ('crockliffe60','Comics & Illustration'),
    ('jstares61','Design & Tech'),
    ('lwiseman62','Arts'),
    ('vtwelftree63','Games'),
    ('darnison64','Design & Tech'),
    ('chann65','Music'),
    ('lranyelld66',NULL),
    ('jgurrado67','Music'),
    ('jstrutley68','Food & Craft'),
    ('splimmer69','Games'),
    ('ctripony6a','Games'),
    ('fbellow6b','Design & Tech'),
    ('dayer6c','Comics & Illustration'),
    ('lladd6d','Film'),
    ('dpolden6e','Food & Craft'),
    ('flowery6f','Comics & Illustration'),
    ('mbelderson6g','Food & Craft'),
    ('msnellman6h','Food & Craft'),
    ('gwelton6i','Comics & Illustration'),
    ('wleeburne6j','Arts'),
    ('thamsley6k','Arts'),
    ('ckliment6l','Games'),
    ('hvain6m','Food & Craft'),
    ('oalsop6n','Music'),
    ('hcawkwell6o','Games'),
    ('egaze6p','Food & Craft'),
    ('nhabens6q','Games'),
    ('nyeandel6r','Comics & Illustration'),
    ('tditter6s',NULL),
    ('pantonowicz6t','Food & Craft'),
    ('smogey6u','Comics & Illustration'),
    ('mlorans6v','Games'),
    ('adoxey6w','Games'),
    ('psarjeant6x','Design & Tech');
